import ReactModal from "react-modal";

export const ReactModalConfig: ReactModal.Styles = {
	content: {
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		border: "none",
		borderRadius: "4px",
		padding: "20px",
		top: "50%",
		left: "50%",
		right: "auto",
		bottom: "auto",
		// transform: "translate(-50%, -50%)",
		maxWidth: "500px",
		overflow: "auto",
		WebkitOverflowScrolling: "touch",
		outline: "none",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-between",
		alignItems: "center",
		// width: "100%",
		// height: "100%",
	},
	overlay: {
		position: "fixed",
		top: "25%",
		left: "25%",
		right: "25%",
		bottom: "50%",
		backgroundColor: "rgba(0, 0, 0, 0.75)",
		zIndex: 3,
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		width: "50vw",
		height: "50vh",
	},
};
